### ISSUE TITLE
[SUGERENCIA] Controlar Ejercitos de la partida

### ISSUE THREAD

**Issue by YeronBM** [SantiGonzalezLago/WarhammerEloWebapp#1]
**¿Qué característica quieres ver implementada?**
Creo que comtrolar el tipo de partida (casual 500 pts, narrativo, etc) podriía ser interesante.
Además creo que controlar el tamaño de la partida (500 pts, 1000 pts, 2000, puntos) y el ejercito (marines, necrones, tiránidos, etc).

**¿Por qué la consideras necesaria?**
Porque? Porque quiero saber con que me apalizas. A cuantos puntos

**Información adicional**
Añade cualquier otra información sobre la funcionalidad aquí.

**Comment by SantiGonzalezLago** [comment]
Realizado
